ADD_SCENE(unitemp, menu, Menu)
ADD_SCENE(unitemp, help, Help)
ADD_SCENE(unitemp, about, About)
ADD_SCENE(unitemp, settings, Settings)
ADD_SCENE(unitemp, monitor, Monitor)
ADD_SCENE(unitemp, sensors_list, SensorsList)
